version: "3"

services: 
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: rails s -p 3000 -b 0.0.0.0
    depends_on: 
      - db
      - redis
  db:
    image: postgres:9.6
    ports:
      - "8001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:3

volumes:
  db-data: