version: "2"

services: 
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=mysecretkey
      - RAILS_SERVE_STATIC_FILES=true
    command: rails s -p 80 -b 0.0.0.0
    depends_on: 
      - db
  db:
    image: postgres